"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 06:28:15.578407
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_state',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('detail_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_target_type'), ['target_type'], unique=False)

    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('schema_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_path', sa.String(length=500), nullable=False),
    sa.Column('schema_hash', sa.String(length=64), nullable=False),
    sa.Column('definitions_json', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schema_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schema_snapshot_job_path'), ['job_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_schema_snapshot_schema_hash'), ['schema_hash'], unique=False)

    op.create_table('target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_path', sa.String(length=500), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('overlap_policy', sa.String(length=10), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('schema_hash', sa.String(length=64), nullable=True),
    sa.Column('schema_error', sa.Text(), nullable=True),
    sa.Column('timer_trigger_detected', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_path')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('cron_expr', sa.String(length=100), nullable=True),
    sa.Column('once_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('params_pinned', sa.Boolean(), nullable=False),
    sa.Column('missed_policy', sa.String(length=10), nullable=False),
    sa.Column('grace_minutes', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('baseline_schema_hash', sa.String(length=64), nullable=True),
    sa.Column('pinned_params_json', sa.JSON(), nullable=True),
    sa.Column('generated_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('param_override',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('param_name', sa.String(length=200), nullable=False),
    sa.Column('value_template', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'param_name')
    )
    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('schema_hash', sa.String(length=64), nullable=True),
    sa.Column('queue_id', sa.Integer(), nullable=True),
    sa.Column('build_number', sa.Integer(), nullable=True),
    sa.Column('build_url', sa.String(length=1000), nullable=True),
    sa.Column('retry_of_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'scheduled_at')
    )
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_schedule_id'), ['schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_target_id'), ['target_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_target_id'))
        batch_op.drop_index(batch_op.f('ix_run_status'))
        batch_op.drop_index(batch_op.f('ix_run_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_run_schedule_id'))

    op.drop_table('run')
    op.drop_table('param_override')
    op.drop_table('schedule')
    op.drop_table('target')
    with op.batch_alter_table('schema_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schema_snapshot_schema_hash'))
        batch_op.drop_index(batch_op.f('ix_schema_snapshot_job_path'))

    op.drop_table('schema_snapshot')
    op.drop_table('category')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_target_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    op.drop_table('app_state')
    # ### end Alembic commands ###
